import { GetStaticProps } from "next";
import React from "react";
import { postFilePaths, POSTS_PATH } from "blog/utils";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { Link } from "components/Link";

type BlogProps = {
  posts: {
    frontMatter: { title: string; description?: string };
    filePath: string;
  }[];
};

const Blog = ({ posts }: BlogProps) => {
  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>mdx-bundler</code>.
      </p>
      <ul>
        {posts.map((post) => {
          const slug = post.filePath.replace(/\.mdx?$/, "");

          return (
            <li key={post.filePath}>
              <Link as={`/blog/${slug}`} href={`/blog/[slug]`}>
                <a>{post.frontMatter.title}</a>
              </Link>
            </li>
          );
        })}
      </ul>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    console.log(source);
    const { data } = matter(source);

    return {
      frontMatter: data,
      filePath,
    };
  });

  return { props: { posts } };
};

export default Blog;
